DROP SCHEMA IF EXISTS "Pokemon" CASCADE;
DROP SCHEMA IF EXISTS "Content" CASCADE;
DROP SCHEMA IF EXISTS "Messaging" CASCADE;
DROP SCHEMA IF EXISTS "Localization" CASCADE;
DROP SCHEMA IF EXISTS "Identity" CASCADE;
DROP SCHEMA IF EXISTS "Logging" CASCADE;
DROP SCHEMA IF EXISTS "Krakenar" CASCADE;
DROP SCHEMA IF EXISTS "EventSourcing" CASCADE;
DROP TABLE IF EXISTS "__EFMigrationsHistory";
