// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PokeCraft.Cms.Infrastructure;

#nullable disable

namespace PokeCraft.Cms.PostgreSQL.Migrations
{
    [DbContext(typeof(PokemonContext))]
    [Migration("20260424050744_CreateFormTables")]
    partial class CreateFormTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PokeCraft.Cms.Infrastructure.Entities.AbilityEntity", b =>
                {
                    b.Property<int>("AbilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AbilityId"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("StreamId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("UniqueId")
                        .HasColumnType("uuid");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("AbilityId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("IsPublished");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.HasIndex("StreamId")
                        .IsUnique();

                    b.HasIndex("UniqueId")
                        .IsUnique();

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("UpdatedOn");

                    b.HasIndex("Version");

                    b.ToTable("Abilities", "Pokemon");
                });

            modelBuilder.Entity("PokeCraft.Cms.Infrastructure.Entities.FormAbilityEntity", b =>
                {
                    b.Property<int>("FormId")
                        .HasColumnType("integer");

                    b.Property<int>("AbilityId")
                        .HasColumnType("integer");

                    b.Property<string>("Slot")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("FormId", "AbilityId");

                    b.HasIndex("AbilityId");

                    b.HasIndex("Slot");

                    b.ToTable("FormAbilities", "Pokemon");
                });

            modelBuilder.Entity("PokeCraft.Cms.Infrastructure.Entities.FormEntity", b =>
                {
                    b.Property<int>("FormId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FormId"));

                    b.Property<byte>("BaseAttack")
                        .HasColumnType("smallint");

                    b.Property<byte>("BaseDefense")
                        .HasColumnType("smallint");

                    b.Property<byte>("BaseHP")
                        .HasColumnType("smallint");

                    b.Property<byte>("BaseSpecialAttack")
                        .HasColumnType("smallint");

                    b.Property<byte>("BaseSpecialDefense")
                        .HasColumnType("smallint");

                    b.Property<byte>("BaseSpeed")
                        .HasColumnType("smallint");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("HasGenderDifferences")
                        .HasColumnType("boolean");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<bool>("IsBattleOnly")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMega")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PrimaryType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("SecondaryType")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("StreamId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("UniqueId")
                        .HasColumnType("uuid");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VarietyId")
                        .HasColumnType("integer");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.Property<byte>("YieldAttack")
                        .HasColumnType("smallint");

                    b.Property<byte>("YieldDefense")
                        .HasColumnType("smallint");

                    b.Property<int>("YieldExperience")
                        .HasColumnType("integer");

                    b.Property<byte>("YieldHP")
                        .HasColumnType("smallint");

                    b.Property<byte>("YieldSpecialAttack")
                        .HasColumnType("smallint");

                    b.Property<byte>("YieldSpecialDefense")
                        .HasColumnType("smallint");

                    b.Property<byte>("YieldSpeed")
                        .HasColumnType("smallint");

                    b.HasKey("FormId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("HasGenderDifferences");

                    b.HasIndex("Height");

                    b.HasIndex("IsBattleOnly");

                    b.HasIndex("IsDefault");

                    b.HasIndex("IsMega");

                    b.HasIndex("IsPublished");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.HasIndex("PrimaryType");

                    b.HasIndex("SecondaryType");

                    b.HasIndex("StreamId")
                        .IsUnique();

                    b.HasIndex("UniqueId")
                        .IsUnique();

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("UpdatedOn");

                    b.HasIndex("VarietyId");

                    b.HasIndex("Version");

                    b.HasIndex("Weight");

                    b.HasIndex("YieldExperience");

                    b.ToTable("Forms", "Pokemon");
                });

            modelBuilder.Entity("PokeCraft.Cms.Infrastructure.Entities.MoveEntity", b =>
                {
                    b.Property<int>("MoveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MoveId"));

                    b.Property<byte?>("Accuracy")
                        .HasColumnType("smallint");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<byte?>("Power")
                        .HasColumnType("smallint");

                    b.Property<byte>("PowerPoints")
                        .HasColumnType("smallint");

                    b.Property<string>("StreamId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("UniqueId")
                        .HasColumnType("uuid");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("MoveId");

                    b.HasIndex("Accuracy");

                    b.HasIndex("Category");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("IsPublished");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.HasIndex("Power");

                    b.HasIndex("PowerPoints");

                    b.HasIndex("StreamId")
                        .IsUnique();

                    b.HasIndex("Type");

                    b.HasIndex("UniqueId")
                        .IsUnique();

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("UpdatedOn");

                    b.HasIndex("Version");

                    b.ToTable("Moves", "Pokemon");
                });

            modelBuilder.Entity("PokeCraft.Cms.Infrastructure.Entities.SpeciesEntity", b =>
                {
                    b.Property<int>("SpeciesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SpeciesId"));

                    b.Property<byte>("BaseFriendship")
                        .HasColumnType("smallint");

                    b.Property<byte>("CatchRate")
                        .HasColumnType("smallint");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<byte>("EggCycles")
                        .HasColumnType("smallint");

                    b.Property<string>("GrowthRate")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<string>("PrimaryEggGroup")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("SecondaryEggGroup")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("StreamId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("UniqueId")
                        .HasColumnType("uuid");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("SpeciesId");

                    b.HasIndex("BaseFriendship");

                    b.HasIndex("CatchRate");

                    b.HasIndex("Category");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("EggCycles");

                    b.HasIndex("GrowthRate");

                    b.HasIndex("IsPublished");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.HasIndex("PrimaryEggGroup");

                    b.HasIndex("SecondaryEggGroup");

                    b.HasIndex("StreamId")
                        .IsUnique();

                    b.HasIndex("UniqueId")
                        .IsUnique();

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("UpdatedOn");

                    b.HasIndex("Version");

                    b.ToTable("Species", "Pokemon");
                });

            modelBuilder.Entity("PokeCraft.Cms.Infrastructure.Entities.VarietyEntity", b =>
                {
                    b.Property<int>("VarietyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VarietyId"));

                    b.Property<bool>("CanChangeForm")
                        .HasColumnType("boolean");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<byte?>("GenderRatio")
                        .HasColumnType("smallint");

                    b.Property<string>("Genus")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer");

                    b.Property<string>("StreamId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("UniqueId")
                        .HasColumnType("uuid");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("VarietyId");

                    b.HasIndex("CanChangeForm");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("GenderRatio");

                    b.HasIndex("Genus");

                    b.HasIndex("IsDefault");

                    b.HasIndex("IsPublished");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.HasIndex("SpeciesId");

                    b.HasIndex("StreamId")
                        .IsUnique();

                    b.HasIndex("UniqueId")
                        .IsUnique();

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("UpdatedOn");

                    b.HasIndex("Version");

                    b.ToTable("Varieties", "Pokemon");
                });

            modelBuilder.Entity("PokeCraft.Cms.Infrastructure.Entities.FormAbilityEntity", b =>
                {
                    b.HasOne("PokeCraft.Cms.Infrastructure.Entities.AbilityEntity", "Ability")
                        .WithMany("Forms")
                        .HasForeignKey("AbilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeCraft.Cms.Infrastructure.Entities.FormEntity", "Form")
                        .WithMany("Abilities")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ability");

                    b.Navigation("Form");
                });

            modelBuilder.Entity("PokeCraft.Cms.Infrastructure.Entities.FormEntity", b =>
                {
                    b.HasOne("PokeCraft.Cms.Infrastructure.Entities.VarietyEntity", "Variety")
                        .WithMany("Forms")
                        .HasForeignKey("VarietyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Variety");
                });

            modelBuilder.Entity("PokeCraft.Cms.Infrastructure.Entities.VarietyEntity", b =>
                {
                    b.HasOne("PokeCraft.Cms.Infrastructure.Entities.SpeciesEntity", "Species")
                        .WithMany("Varieties")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Species");
                });

            modelBuilder.Entity("PokeCraft.Cms.Infrastructure.Entities.AbilityEntity", b =>
                {
                    b.Navigation("Forms");
                });

            modelBuilder.Entity("PokeCraft.Cms.Infrastructure.Entities.FormEntity", b =>
                {
                    b.Navigation("Abilities");
                });

            modelBuilder.Entity("PokeCraft.Cms.Infrastructure.Entities.SpeciesEntity", b =>
                {
                    b.Navigation("Varieties");
                });

            modelBuilder.Entity("PokeCraft.Cms.Infrastructure.Entities.VarietyEntity", b =>
                {
                    b.Navigation("Forms");
                });
#pragma warning restore 612, 618
        }
    }
}
